project:
  type: website
  output-dir: docs
  render:
    - annexe.qmd     

files:
  - Tp_apprentissage_statistique.pdf

website:
  repo-url: https://github.com/Qufst/Tp_Svm_Festor_Quentin
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Tp3_Svm"
  sidebar: true
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/Qufst/Tp_Svm_Festor_Quentin
        text: GitHub
    left:
      - text: "PDF"
        href: Tp_apprentissage_statistique.pdf
      - text: "Annexe"
        href: annexe.qmd 


jupyter: python3

editor: visual

publish:
  gh-pages:
    branch: gh-pages
    orphan: true
