project:
  type: website
  render:
    - annexe.qmd  # Rend le fichier annexe.qmd en HTML
  
# Inclure le PDF dans la sortie du site
files:
  - Tp_apprentissage_statistique.pdf

website:
  repo-url: https://github.com/Qufst/Tp_Svm_Festor_Quentin
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Tp3_Svm"
  sidebar: true
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/Qufst/Tp_Svm_Festor_Quentin
        text: GitHub
    left:
      - text: "Annexe"
        href: annexe.qmd   # Lien vers le fichier annexe.qmd (rendu en HTML)
      - text: "PDF"
        href: Tp_apprentissage_statistique.pdf   # Lien vers le fichier PDF statique

jupyter: python3

editor: visual
