name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - numpy
  - nbformat
  - scikit-learn  
  - seaborn
  - pandas        
  - scipy         
  - ipykernel
  - pathlib
  - time
  - warnings
  - pyyaml    
