name: Actualiser le site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installer Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: activer l'env
        run: micromamba activate myenv


      #- name: nbformat
      #  run: python3 -m pip install jupyter nbformat

            
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Actualiser le site avec Quarto
        run: quarto publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}