name: Actualiser le site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installer Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: myenv
          environment-file: environment.yml

            
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Actualiser le site avec Quarto
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
